#!/usr/bin/env python3
"""
Multi-source matrix builder for Nepenthe Journal.

Combines data from 5 sources into a unified substance database keyed by
PubChem CID, output as a JournalSnapshot JSON file the app loads at startup.

Sources:
  1. PsychonautWiki SMW   - doses, durations, effects, ROAs, classes, interactions
  2. PubChem              - CID, molecular formula, weight, SMILES, InChIKey, LogP
  3. TripSit              - aliases, categories, Erowid links, interaction chart
  4. Wikidata             - cross-references (ChEMBL ID, DrugBank ID, CAS, etc.)
  5. ChEMBL               - bioactivity data (IC50/Ki/EC50 at molecular targets)

Pipeline stages:
  1. Load SMW seed (generated by scripts/smw_dump.py)
  2. Resolve PubChem CIDs by substance name (cached)
  3. Fetch PubChem molecular properties by CID batch
  4. Fetch TripSit drugs + combos
  5. Cross-reference names: SMW ↔ TripSit
  6. Merge substances (CID-based IDs, filter categories, keep botanicals)
  7. Build interactions (SMW + TripSit combos)
  8. Fetch Wikidata cross-references (cached)
  9. Fetch ChEMBL bioactivities (cached)
  10. Write JournalSnapshot JSON

Usage:
    # Full rebuild (downloads everything)
    python scripts/matrix_build.py --input seed.json --output final.json --verbose

    # Incremental update (uses cached API results)
    python scripts/matrix_build.py --input seed.json --output final.json --verbose

    # Full refresh (delete caches, re-download)
    python scripts/matrix_build.py --input seed.json --output final.json --refresh --verbose

Cache files (*_cache.json) persist between runs so only new/missing data
is fetched. Delete them to force a full re-download.

Requires: httpx (pip install httpx)
"""

import argparse
import json
import os
import sys
import time
import urllib.parse
from datetime import datetime, timezone
from typing import Any

import httpx

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SMW_API = "https://psychonautwiki.org/w/api.php"
PUBCHEM_BASE = "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
TRIPSIT_API = "https://api.tripsit.me"
TRIPSIT_COMBOS = "https://raw.githubusercontent.com/tripsit/drugs/master/combos.json"
USER_AGENT = "NepentheJournal/1.0 ETL pipeline"
PUBCHEM_DELAY = 0.2  # seconds between PubChem lookups (be polite)
HTTP_TIMEOUT = 60.0

_client = httpx.Client(headers={"User-Agent": USER_AGENT}, timeout=HTTP_TIMEOUT)

# PubChem property names to fetch
PUBCHEM_PROPS = "MolecularWeight,MolecularFormula,XLogP,HBondDonorCount,HBondAcceptorCount,SMILES,InChIKey,IUPACName"

# TripSit status -> InteractionRisk mapping
TRIPSIT_RISK_MAP = {
    "Dangerous": "DANGEROUS",
    "Unsafe": "UNSAFE",
    "Caution": "UNSAFE",
    "Low Risk & Decrease": "LOW",
    "Low Risk & No Synergy": "LOW",
    "Low Risk & Synergy": "LOW",
}

# Names that PubChem doesn't resolve and need manual CID overrides
MANUAL_CID_OVERRIDES: dict[str, int] = {
    "PCP": 6449,              # Phencyclidine
    "DXM": 5360696,           # Dextromethorphan
    "THC": 16078,             # Tetrahydrocannabinol (delta-9)
    "LSA": 442075,            # Lysergic acid amide
    "GHB": 10413,             # Gamma-Hydroxybutyric acid
    "GBL": 7035,              # Gamma-Butyrolactone
    "Kava": 5281052,          # Kavalactone (yangonin)
    "Salvinorin A": 128563,   # Salvinorin A
}

# Substances that are mixtures/plants/no single CID
NO_CID_NAMES: set[str] = {
    "Ayahuasca", "Changa", "Coca", "Cocoa", "Kratom", "Salvia divinorum",
    "Amanita muscaria", "Psilocybe cubensis", "Morning glory",
    "Banisteriopsis caapi", "Peganum harmala", "Tabernanthe iboga",
    "Mandragora", "Mandragora officinarum (botany)",
    "Piper nigrum (botany)", "Datura (botany)", "Datura",
    "Hyoscyamus niger (botany)", "Anadenanthera peregrina",
    "Atropa belladonna", "Psilocybin mushrooms",
}

# Names that need alias lookup for PubChem
PUBCHEM_NAME_OVERRIDES: dict[str, str] = {
    "Nitrous": "nitrous oxide",
    "PMA": "paramethoxyamphetamine",
    "PMMA": "paramethoxymethamphetamine",
    "DOB": "brolamfetamine",
    "DOC": "dimethoxy-chloroamphetamine",
    "DOI": "iodo-dimethoxyamphetamine",
    "DOM": "dimethoxy-methylamphetamine",
    "2C-T-2": "2,5-dimethoxy-4-ethylthiophenethylamine",
    "2C-T-7": "2,5-dimethoxy-4-propylthiophenethylamine",
    "5-MeO-DiPT": "5-methoxy-diisopropyltryptamine",
    "5-MeO-MiPT": "5-methoxy-methylisopropyltryptamine",
    "4-AcO-DMT": "psilacetin",
    "4-HO-MET": "methylcybin",
    "4-HO-MiPT": "miprocin",
    "EPH": "ethylphenidate",
}

# ---------------------------------------------------------------------------
# Stage 1: PubChem CID resolution
# ---------------------------------------------------------------------------


def pubchem_cid(name: str) -> int | None:
    """Resolve a substance name to a PubChem CID."""
    # Check manual overrides first
    if name in MANUAL_CID_OVERRIDES:
        return MANUAL_CID_OVERRIDES[name]

    # Check name override
    query = PUBCHEM_NAME_OVERRIDES.get(name, name)

    try:
        url = f"{PUBCHEM_BASE}/compound/name/{urllib.parse.quote(query)}/cids/JSON"
        r = _client.get(url)
        if r.status_code == 200:
            data = r.json()
            cids = data.get("IdentifierList", {}).get("CID", [])
            return cids[0] if cids else None
        return None
    except Exception:
        return None


def pubchem_batch_properties(cids: list[int]) -> dict[int, dict[str, Any]]:
    """Fetch molecular properties for a batch of CIDs via POST."""
    results: dict[int, dict[str, Any]] = {}
    if not cids:
        return results

    # Split into batches of 50 (PubChem max)
    batch_size = 50
    for i in range(0, len(cids), batch_size):
        batch = cids[i:i + batch_size]
        try:
            url = f"{PUBCHEM_BASE}/compound/cid/{','.join(str(c) for c in batch)}/property/{PUBCHEM_PROPS}/JSON"
            r = _client.get(url)
            if r.status_code == 200:
                data = r.json()
                for prop in data.get("PropertyTable", {}).get("Properties", []):
                    cid = prop.get("CID")
                    if cid:
                        results[cid] = prop
        except Exception:
            pass
        time.sleep(0.1)

    return results


def pubchem_property(cid: int) -> dict[str, Any] | None:
    """Fetch molecular properties for a single CID."""
    try:
        url = f"{PUBCHEM_BASE}/compound/cid/{cid}/property/{PUBCHEM_PROPS}/JSON"
        r = _client.get(url)
        if r.status_code == 200:
            data = r.json()
            props = data.get("PropertyTable", {}).get("Properties", [])
            if props:
                return props[0]
        return None
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Stage 2: TripSit data
# ---------------------------------------------------------------------------


def tripsit_get_all_drugs() -> dict[str, Any]:
    """Fetch all TripSit drug data from GitHub raw (most reliable source)."""
    try:
        r = _client.get(
            "https://raw.githubusercontent.com/tripsit/drugs/master/drugs.json",
            follow_redirects=True
        )
        if r.status_code == 200:
            return r.json()
        return {}
    except Exception:
        return {}


def tripsit_get_combos() -> dict[str, Any]:
    """Fetch TripSit interaction combos."""
    try:
        r = _client.get(TRIPSIT_COMBOS, follow_redirects=True)
        if r.status_code == 200:
            return r.json()
        return {}
    except Exception:
        return {}


def tripsit_name_index(drugs: dict[str, Any]) -> dict[str, str]:
    """
    Build a name -> canonical_key index from TripSit drugs.
    Includes all aliases pointing to the canonical form.
    """
    index: dict[str, str] = {}
    for key, drug in drugs.items():
        # Lowercase canonical key
        index[key.lower()] = key
        # Aliases
        aliases = drug.get("aliases", []) if isinstance(drug, dict) else []
        for alias in aliases:
            index[alias.lower().strip()] = key
        # Pretty name
        pretty = drug.get("pretty_name", "") if isinstance(drug, dict) else ""
        if pretty and pretty.lower() != key.lower():
            index[pretty.lower()] = key
    return index


# ---------------------------------------------------------------------------
# Stage 3: SMW data (load existing seed)
# ---------------------------------------------------------------------------


def load_smw_seed(path: str) -> dict[str, Any]:
    """Load the existing SMW-generated seed JSON."""
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def smw_get_all_substance_names() -> list[str]:
    """Fetch fresh substance list from SMW (fallback if no seed)."""
    try:
        r = _client.get(
            f"{SMW_API}?action=ask&query=%5B%5BCategory%3ASubstance%5D%5D%7Climit%3D500&format=json"
        )
        data = r.json()
        names = list(data["query"]["results"].keys())
        return [n for n in names if not n.startswith("Experience:")]
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Merging logic
# ---------------------------------------------------------------------------


def build_chemical_properties(pubchem_data: dict[str, Any] | None) -> dict[str, Any] | None:
    """Build ChemicalProperties object from PubChem data."""
    if not pubchem_data:
        return None
    cp = {
        "cid": pubchem_data.get("CID"),
        "molecularFormula": pubchem_data.get("MolecularFormula"),
        "molecularWeight": pubchem_data.get("MolecularWeight"),
        "smiles": pubchem_data.get("SMILES"),
        "inchiKey": pubchem_data.get("InChIKey"),
        "iupacName": pubchem_data.get("IUPACName"),
        "xlogP": pubchem_data.get("XLogP"),
        "hBondDonorCount": pubchem_data.get("HBondDonorCount"),
        "hBondAcceptorCount": pubchem_data.get("HBondAcceptorCount"),
    }
    # Remove None values
    return {k: v for k, v in cp.items() if v is not None}


def match_name_to_tripsit(
    name: str, aliases: list[str], ts_index: dict[str, str], ts_drugs: dict[str, Any]
) -> tuple[str | None, dict[str, Any] | None]:
    """
    Try to match a substance name or its aliases to a TripSit drug entry.
    Returns (canonical_key, drug_data).
    """
    # Try primary name
    key = name.lower().strip()
    if key in ts_index:
        ts_key = ts_index[key]
        return ts_key, ts_drugs.get(ts_key)

    # Try aliases
    for alias in aliases:
        alias_key = alias.lower().strip()
        if alias_key in ts_index:
            ts_key = ts_index[alias_key]
            return ts_key, ts_drugs.get(ts_key)

    return None, None


def merge_substance(
    smw_sub: dict[str, Any],
    cid: int | None,
    pubchem_props: dict[str, Any] | None,
    tripsit_drug: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Merge SMW + PubChem + TripSit data into a unified substance record.
    CID becomes the primary ID where available.
    """
    name = smw_sub["name"]
    old_id = smw_sub["id"]

    # New ID: prefer CID
    new_id = f"cid:{cid}" if cid else old_id

    # Merge aliases from all sources
    aliases = list(smw_sub.get("aliases", []))
    ts_aliases = tripsit_drug.get("aliases", []) if tripsit_drug else []
    for a in ts_aliases:
        if a.lower() != name.lower() and a not in aliases:
            aliases.append(a)

    # Merge effects
    effects = list(smw_sub.get("effects", []))
    ts_effects = tripsit_drug.get("formatted_effects", []) if tripsit_drug else []
    for e in ts_effects:
        if e not in effects:
            effects.append(e)

    # Merge categories/classes
    substance_class = list(smw_sub.get("substanceClass", []))
    ts_categories = tripsit_drug.get("categories", []) if tripsit_drug else []
    if ts_categories:
        substance_class.extend([c for c in ts_categories if c not in substance_class])

    # Add Erowid link from TripSit if available
    erowid_url = ""
    if tripsit_drug:
        links = tripsit_drug.get("links", {})
        if isinstance(links, dict):
            erowid_url = links.get("experiences", "")

    # Track sources
    sources = ["psychonautwiki"]
    if cid:
        sources.append("pubchem")
    if tripsit_drug:
        sources.append("tripsit")

    return {
        "id": new_id,
        "oldId": old_id if old_id != new_id else None,
        "cid": cid,
        "docType": "substance",
        "createdAt": smw_sub.get("createdAt") or smw_sub.get("cachedAt"),
        "updatedAt": smw_sub.get("updatedAt") or smw_sub.get("cachedAt"),
        "deviceOrigin": "system",
        "pwikiId": smw_sub.get("pwikiId") or name,
        "name": name,
        "aliases": aliases,
        "summary": smw_sub.get("summary"),
        "substanceClass": substance_class,
        "routesOfAdministration": smw_sub.get("routesOfAdministration", []),
        "dosageBands": smw_sub.get("dosageBands", {}),
        "durationProfile": smw_sub.get("durationProfile", {}),
        "addictionPotential": smw_sub.get("addictionPotential"),
        "toxicity": smw_sub.get("toxicity", []),
        "crossTolerances": smw_sub.get("crossTolerances", []),
        "effects": effects,
        "chemicalProperties": build_chemical_properties(pubchem_props),
        "erowidUrl": erowid_url,
        "sources": sources,
        "cachedAt": smw_sub.get("cachedAt"),
        "sourceVersion": "pwiki-smw-v2",
        "userAnnotations": {},
    }


def merge_interactions(
    smw_interactions: list[dict[str, Any]],
    combos_data: dict[str, Any],
    name_to_cid: dict[str, int | None],
    pwiki_to_new_id: dict[str, str],  # "pwiki:lsd" -> "cid:5761"
    now_ms: int,
) -> list[dict[str, Any]]:
    """
    Merge SMW interactions with TripSit combo data.
    Both are keyed by substance name/category; we map to CIDs.
    """
    seen: set[str] = set()
    merged: list[dict[str, Any]] = []

    def add_interaction(a: str, b: str, risk: str, notes: str | None = None, sources_list: list[str] | None = None):
        # Sort IDs
        ids = sorted([a, b])
        int_id = f"interaction:{ids[0]}:{ids[1]}"
        if int_id in seen:
            return
        seen.add(int_id)
        merged.append({
            "id": int_id,
            "docType": "interaction",
            "createdAt": now_ms,
            "updatedAt": now_ms,
            "deviceOrigin": "system",
            "substanceAId": ids[0],
            "substanceBId": ids[1],
            "riskLevel": risk,
            "description": notes,
            "sources": sources_list or ["psychonautwiki"],
        })

    # Process SMW interactions - map old pwiki: IDs to new cid: IDs
    for interaction in smw_interactions:
        old_a = interaction["substanceAId"]
        old_b = interaction["substanceBId"]
        new_a = pwiki_to_new_id.get(old_a, old_a)
        new_b = pwiki_to_new_id.get(old_b, old_b)
        add_interaction(
            new_a, new_b, interaction["riskLevel"],
        )

    # Process TripSit combos
    name_to_id: dict[str, str] = {}
    for orig_name, cid in name_to_cid.items():
        name_lower = orig_name.lower().strip()
        name_to_id[name_lower] = f"cid:{cid}" if cid else f"pwiki:{orig_name.lower().replace(' ', '_')}"
        # Also add pwiki ID
        name_to_id[orig_name.lower()] = f"cid:{cid}" if cid else f"pwiki:{orig_name.lower().replace(' ', '_')}"

    # Map combo interactions
    for combo_key, combo_targets in combos_data.items():
        sub_a_id = name_to_id.get(combo_key.lower())
        if not sub_a_id:
            continue

        for target_key, combo_info in combo_targets.items():
            sub_b_id = name_to_id.get(target_key.lower())
            if not sub_b_id:
                continue

            ts_risk = combo_info.get("status", "")
            risk = TRIPSIT_RISK_MAP.get(ts_risk, "UNKNOWN")
            note = combo_info.get("note", "")
            sources_list = ["tripsit"]
            if combo_info.get("sources"):
                sources_list.append("peer-reviewed")

            add_interaction(sub_a_id, sub_b_id, risk, note or None, sources_list)

    return merged


# ---------------------------------------------------------------------------
# Stage: Wikidata cross-references
# ---------------------------------------------------------------------------

WIKIDATA_PROPS = {
    "P662": "pubchemCid", "P592": "chemblId", "P715": "drugbankId",
    "P595": "iupharId", "P1117": "cas", "P661": "chemspiderId",
    "P652": "unii", "P267": "atcCode", "P2084": "keggId",
    "P2057": "hmdbId", "P683": "chebiId", "P232": "ecNumber",
    "P665": "rxnorm", "P3117": "dsstoxCid",
}
WIKIDATA_STANDARD_PROPS = ["chemblId", "drugbankId", "iupharId", "chemspiderId",
                           "unii", "chebiId", "atcCode"]


def wikidata_batch_fetch(cids: list[int], batch_size: int = 30) -> dict[int, dict[str, Any]]:
    """
    Batch Wikidata lookup using per-CID API calls with concurrent workers.
    Returns {cid: {qid, chemblId, drugbankId, ...}}
    """
    import concurrent.futures

    def lookup_single(cid: int) -> tuple[int, dict[str, Any]]:
        try:
            # Step 1: Find QID via haswbstatement search
            r = _client.get(
                "https://www.wikidata.org/w/api.php",
                params={"action": "query", "list": "search",
                        "srsearch": f"haswbstatement:P662={cid}",
                        "srlimit": 1, "format": "json"},
                timeout=15,
            )
            if r.status_code == 429:
                time.sleep(3)
                r = _client.get(
                    "https://www.wikidata.org/w/api.php",
                    params={"action": "query", "list": "search",
                            "srsearch": f"haswbstatement:P662={cid}",
                            "srlimit": 1, "format": "json"},
                    timeout=15,
                )
            if r.status_code != 200:
                return cid, {}
            results = r.json().get("query", {}).get("search", [])
            if not results:
                return cid, {}
            qid = results[0]["title"]

            # Step 2: Fetch full entity for cross-references
            r2 = _client.get(
                f"https://www.wikidata.org/wiki/Special:EntityData/{qid}.json",
                timeout=15,
            )
            if r2.status_code != 200:
                return cid, {"qid": qid}

            claims = r2.json()["entities"][qid].get("claims", {})
            entry: dict[str, Any] = {"qid": qid}

            wd_pid_map = {
                "P592": "chemblId", "P715": "drugbankId", "P595": "iupharId",
                "P661": "chemspiderId", "P652": "unii", "P683": "chebiId",
                "P267": "atcCode", "P1117": "cas", "P2084": "keggId",
                "P2057": "hmdbId", "P665": "rxnorm", "P3117": "dsstoxCid",
            }
            for pid, key in wd_pid_map.items():
                if pid in claims:
                    snak = claims[pid][0]["mainsnak"]
                    if snak["snaktype"] == "value":
                        dv = snak["datavalue"]["value"]
                        if isinstance(dv, dict):
                            dv = dv.get("id", str(dv))
                        entry[key] = dv
            return cid, entry
        except Exception:
            return cid, {}

    result: dict[int, dict[str, Any]] = {}

    # Use ThreadPoolExecutor for concurrent lookups
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:
        fut_map = {pool.submit(lookup_single, cid): cid for cid in cids}
        done = 0
        for future in concurrent.futures.as_completed(fut_map):
            cid, entry = future.result()
            if entry:
                result[cid] = entry
            done += 1
            # Rate limit: sleep after every 3 completes
            if done % 3 == 0 and done < len(cids):
                time.sleep(1.0)
    return result


def wikidata_fetch_entity(qid: str) -> dict[str, Any]:
    """Fetch Wikidata entity JSON and extract cross-references."""
    result: dict[str, Any] = {"qid": qid}
    try:
        r = _client.get(
            f"https://www.wikidata.org/wiki/Special:EntityData/{qid}.json",
        )
        if r.status_code == 200:
            claims = r.json()["entities"][qid].get("claims", {})
            for pid, label in WIKIDATA_PROPS.items():
                if pid in claims:
                    snak = claims[pid][0]["mainsnak"]
                    if snak["snaktype"] == "value":
                        dv = snak["datavalue"]["value"]
                        if isinstance(dv, dict):
                            dv = dv.get("id", str(dv))
                        result[label] = dv
    except Exception:
        pass
    return result


# ---------------------------------------------------------------------------
# Stage: ChEMBL bioactivity
# ---------------------------------------------------------------------------


def chembl_fetch(chembl_id: str) -> dict[str, Any]:
    """Fetch ChEMBL molecule data and bioactivities."""
    result: dict[str, Any] = {"chemblId": chembl_id}
    if not chembl_id:
        return result

    try:
        # Molecule properties
        r = _client.get(
            f"https://www.ebi.ac.uk/chembl/api/data/molecule/{chembl_id}.json",
        )
        if r.status_code == 200:
            mol = r.json()
            props = mol.get("molecule_properties", {})
            result["mw"] = props.get("mw_freebase")
            result["alogp"] = props.get("alogp")
            result["psa"] = props.get("psa")
            result["ro5Violations"] = props.get("num_ro5_violations")
            # maxPhase can be -1.0 (not applicable) - convert to int
            mp = mol.get("max_phase")
            if mp is not None:
                result["maxPhase"] = int(mp)
            result["prefName"] = mol.get("pref_name")
    except Exception:
        pass

    # Bioactivities: get Ki and IC50 values
    bioact: list[dict[str, Any]] = []
    try:
        for std_type in ["IC50", "Ki", "EC50", "Kd"]:
            r = _client.get(
                "https://www.ebi.ac.uk/chembl/api/data/activity.json",
                params={
                    "molecule_chembl_id": chembl_id,
                    "standard_type": std_type,
                    "limit": 20,
                    "assay_type__in": "B",
                },
            )
            if r.status_code == 200:
                for a in r.json().get("activities", []):
                    bioact.append({
                        "type": std_type,
                        "value": a.get("standard_value"),
                        "units": a.get("standard_units"),
                        "relation": a.get("standard_relation"),
                        "targetId": a.get("target_chembl_id"),
                        "assay": a.get("assay_description", "")[:120] if a.get("assay_description") else "",
                    })
    except Exception:
        pass

    if bioact:
        result["bioactivities"] = bioact
    return result


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="Build unified substance matrix")
    parser.add_argument("--input", "-i", default="", help="Input SMW seed JSON")
    parser.add_argument("--output", "-o", default="unified_seed.json", help="Output path")
    parser.add_argument("--refresh", "-r", action="store_true", help="Delete caches and re-download all data")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    # Refresh: delete all cache files
    if args.refresh:
        for fname in ["pubchem_cid_cache.json", "wikidata_cache.json", "chembl_cache.json"]:
            if os.path.exists(fname):
                os.remove(fname)
                if args.verbose:
                    print(f"[*] Deleted cache: {fname}", file=sys.stderr)

    now_ms = int(datetime.now(timezone.utc).timestamp() * 1000)

    # --- Stage 0: Load or fetch SMW data ---
    if args.input:
        if args.verbose:
            print(f"[*] Loading SMW seed from {args.input}", file=sys.stderr)
        smw_data = load_smw_seed(args.input)
        substances_raw = smw_data.get("substances", [])
        interactions_raw = smw_data.get("interactions", [])
    else:
        if args.verbose:
            print("[*] Fetching fresh SMW data from wiki...", file=sys.stderr)
        # Run the SMW dump inline (simplified: just names + smwbrowse)
        from smw_dump import get_all_substance_names, get_substance_properties, smw_to_substance, smw_to_interactions, get_summaries
        names = get_all_substance_names()
        names = [n for n in names if not n.startswith("Experience:")]
        summaries = get_summaries(names)
        substances_raw = []
        interactions_raw = []
        all_ints: dict[str, dict] = {}
        for i, n in enumerate(names, 1):
            props = get_substance_properties(n)
            sub = smw_to_substance(n, props, summaries.get(n), now_ms)
            substances_raw.append(sub)
            ints = smw_to_interactions(n, props, now_ms)
            for intv in ints:
                all_ints[intv["id"]] = intv
            if args.verbose and i % 50 == 0:
                print(f"  [{i}/{len(names)}] SMW fetch...", file=sys.stderr)
            time.sleep(0.15)
        interactions_raw = list(all_ints.values())

    if args.verbose:
        print(f"[+] Loaded {len(substances_raw)} substances, {len(interactions_raw)} interactions from SMW", file=sys.stderr)

    # --- Stage 1: Resolve PubChem CIDs ---
    if args.verbose:
        print("[*] Resolving PubChem CIDs...", file=sys.stderr)

    # Try loading cached CID map
    pubchem_cid_cache = "pubchem_cid_cache.json"
    name_to_cid: dict[str, int | None] = {}
    cid_to_name: dict[int, str] = {}
    if os.path.exists(pubchem_cid_cache):
        try:
            with open(pubchem_cid_cache) as f:
                raw = json.load(f)
                name_to_cid = {k: (int(v) if v else None) for k, v in raw.items()}
            if args.verbose:
                cached = sum(1 for v in name_to_cid.values() if v is not None)
                print(f"[*] Loaded {cached}/{len(name_to_cid)} cached CIDs", file=sys.stderr)
        except Exception:
            name_to_cid = {}

    resolved_count = 0
    missing_names = [s["name"] for s in substances_raw if s["name"] not in name_to_cid]
    for name in missing_names:
        cid = None
        if name not in NO_CID_NAMES:
            cid = pubchem_cid(name)
            if cid is None:
                sub = next((s for s in substances_raw if s["name"] == name), None)
                if sub:
                    for alias in sub.get("aliases", []):
                        cid = pubchem_cid(alias)
                        if cid:
                            break
        name_to_cid[name] = cid
        if cid:
            cid_to_name[cid] = name
            resolved_count += 1
        time.sleep(PUBCHEM_DELAY)

    # Save cache
    try:
        with open(pubchem_cid_cache, "w") as f:
            json.dump({k: v for k, v in name_to_cid.items()}, f)
    except Exception:
        pass

    if args.verbose:
        print(f"[+] Resolved {resolved_count}/{len(substances_raw)} CIDs", file=sys.stderr)

    # --- Stage 2: Fetch PubChem properties (batch) ---
    all_cids = [cid for cid in name_to_cid.values() if cid is not None]
    if args.verbose:
        print(f"[*] Fetching PubChem properties for {len(all_cids)} CIDs...", file=sys.stderr)

    cid_props = pubchem_batch_properties(all_cids)
    if args.verbose:
        print(f"[+] Got properties for {len(cid_props)}/{len(all_cids)} CIDs", file=sys.stderr)

    # --- Stage 3: Fetch TripSit data ---
    if args.verbose:
        print("[*] Fetching TripSit drugs...", file=sys.stderr)
    ts_drugs = tripsit_get_all_drugs()
    ts_index = tripsit_name_index(ts_drugs)
    if args.verbose:
        print(f"[+] TripSit has {len(ts_drugs)} drugs", file=sys.stderr)

    if args.verbose:
        print("[*] Fetching TripSit combos...", file=sys.stderr)
    ts_combos = tripsit_get_combos()
    if args.verbose:
        print(f"[+] TripSit combos: {len(ts_combos)} categories", file=sys.stderr)

    # --- Stage 4: Merge substances ---
    if args.verbose:
        print("[*] Merging data sources...", file=sys.stderr)

    merged_substances = []
    ts_match_count = 0

    for sub in substances_raw:
        name = sub["name"]
        cid = name_to_cid.get(name)
        pubchem_data = cid_props.get(cid) if cid else None
        ts_key, ts_drug = match_name_to_tripsit(name, sub.get("aliases", []), ts_index, ts_drugs)
        if ts_drug:
            ts_match_count += 1
        merged = merge_substance(sub, cid, pubchem_data, ts_drug)
        merged_substances.append(merged)

    if args.verbose:
        cid_count = sum(1 for s in merged_substances if s["cid"])
        pchem_count = sum(1 for s in merged_substances if s.get("chemicalProperties"))
        print(f"[+] Merged: {len(merged_substances)} substances", file=sys.stderr)
        print(f"    CID: {cid_count} | PubChem props: {pchem_count} | TripSit match: {ts_match_count}", file=sys.stderr)

    # --- Stage 4b: Filter out conceptual categories (keep real compounds + botanicals) ---
    BOTANICALS = {
        "Salvia divinorum", "Kratom", "Amanita muscaria", "Psilocybe cubensis",
        "Banisteriopsis caapi", "Peganum harmala", "Atropa belladonna",
        "Mandragora", "Tabernanthe iboga", "Datura", "Coca",
        "Morning glory", "Changa", "Ayahuasca", "Anadenanthera peregrina",
        "Blue Lotus", "Psilocybin mushrooms", "Cannabis",
        "Piper nigrum (botany)", "Cocoa",
    }

    def is_real_substance(sub: dict) -> bool:
        if sub.get("cid"):
            return True
        db = sub.get("dosageBands", {})
        dp = sub.get("durationProfile", {})
        has_dose = bool(db and any(v for v in db.values()))
        has_dur = bool(dp and any(v for v in dp.values()))
        if has_dose or has_dur:
            return True
        if sub.get("name") in BOTANICALS:
            return True
        return False

    before = len(merged_substances)
    merged_substances = [s for s in merged_substances if is_real_substance(s)]
    excluded_names = set()
    for s in merged_substances:
        excluded_names.add(s["name"].lower())
    excluded_count = before - len(merged_substances)
    if args.verbose:
        print(f"[+] Filtered: removed {excluded_count} category pages, kept {len(merged_substances)}", file=sys.stderr)

    # --- Stage 5: Merge interactions ---
    # Build old ID -> new ID mapping from merged substances
    pwiki_to_new_id: dict[str, str] = {}
    for sub in merged_substances:
        old_id = sub.get("oldId")
        if old_id and old_id != sub["id"]:
            pwiki_to_new_id[old_id] = sub["id"]

    merged_interactions = merge_interactions(
        interactions_raw, ts_combos, name_to_cid,
        pwiki_to_new_id,
        now_ms,
    )

    if args.verbose:
        print(f"[+] Interactions: {len(merged_interactions)} (SMW: {len(interactions_raw)} + TripSit combos)", file=sys.stderr)

    # --- Stage 6: Wikidata cross-references + ChEMBL bioactivity ---
    cids_with_chembl = [sub["cid"] for sub in merged_substances if sub.get("cid")]
    wd_map: dict[int, dict[str, Any]] = {}

    # Try loading cached Wikidata results
    wikidata_cache_file = "wikidata_cache.json"
    if os.path.exists(wikidata_cache_file):
        try:
            with open(wikidata_cache_file) as f:
                wd_map = {int(k): v for k, v in json.load(f).items()}
            if args.verbose:
                print(f"[*] Loaded {len(wd_map)} cached Wikidata entries", file=sys.stderr)
        except Exception:
            wd_map = {}

    # Fetch missing entries
    missing = [c for c in cids_with_chembl if c not in wd_map]
    if missing:
        if args.verbose:
            print(f"[*] Wikidata lookup for {len(missing)} uncached CIDs...", file=sys.stderr)
        new_wd = wikidata_batch_fetch(missing)
        wd_map.update(new_wd)
        # Save cache
        try:
            with open(wikidata_cache_file, "w") as f:
                json.dump({str(k): v for k, v in wd_map.items()}, f)
        except Exception:
            pass

    if args.verbose:
        print(f"[+] Wikidata: {len(wd_map)}/{len(cids_with_chembl)}", file=sys.stderr)

    # Fetch ChEMBL for those with ChEMBL IDs
    chembl_cache_file = "chembl_cache.json"
    chembl_cache: dict[str, dict[str, Any]] = {}
    if os.path.exists(chembl_cache_file):
        try:
            with open(chembl_cache_file) as f:
                chembl_cache = json.load(f)
            if args.verbose:
                print(f"[*] Loaded {len(chembl_cache)} cached ChEMBL entries", file=sys.stderr)
        except Exception:
            chembl_cache = {}

    chembl_missing = []
    for cid, wd in wd_map.items():
        chembl_id = wd.get("chemblId")
        if chembl_id and chembl_id not in chembl_cache:
            chembl_missing.append((cid, chembl_id))

    chembl_found = 0
    if chembl_missing:
        if args.verbose:
            print(f"[*] Fetching ChEMBL for {len(chembl_missing)} compounds...", file=sys.stderr)
        for cid, chembl_id in chembl_missing:
            ch = chembl_fetch(chembl_id)
            if ch.get("bioactivities"):
                chembl_cache[chembl_id] = ch
                chembl_found += 1
            if len(chembl_cache) % 10 == 0 and args.verbose:
                print(f"  [ChEMBL] {len(chembl_cache)} fetched so far", file=sys.stderr)
        # Save cache
        try:
            with open(chembl_cache_file, "w") as f:
                json.dump(chembl_cache, f)
        except Exception:
            pass
    else:
        if args.verbose:
            print(f"[*] ChEMBL: all {len(chembl_cache)} cached", file=sys.stderr)

    if args.verbose:
        chembl_with_bio = sum(1 for v in chembl_cache.values() if v.get("bioactivities"))
        print(f"[+] ChEMBL bioactivity: {chembl_with_bio} compounds", file=sys.stderr)

    # Merge into substances
    for sub in merged_substances:
        cid = sub.get("cid")
        if cid and cid in wd_map:
            wd = wd_map[cid]
            for key in WIKIDATA_STANDARD_PROPS:
                if key in wd:
                    sub[key] = wd[key]
            # Add ChEMBL data
            chembl_id = wd.get("chemblId")
            if chembl_id and chembl_id in chembl_cache:
                ch = chembl_cache[chembl_id]
                sub["chemblData"] = {
                    "prefName": ch.get("prefName"),
                    "mw": ch.get("mw"),
                    "alogp": ch.get("alogp"),
                    "psa": ch.get("psa"),
                    "ro5Violations": ch.get("ro5Violations"),
                    "maxPhase": ch.get("maxPhase"),
                    "bioactivities": ch.get("bioactivities", []),
                }

    if args.verbose:
        ref_count = sum(1 for s in merged_substances if s.get("chemblId"))
        bc_count = sum(1 for s in merged_substances if s.get("chemblData"))
        print(f"[+] Wikidata cross-refs: {ref_count} | ChEMBL bioactivity: {bc_count}", file=sys.stderr)

    # --- Stage 7: Write output ---
    snapshot = {
        "version": 3,
        "savedAt": now_ms,
        "sessions": [],
        "substances": merged_substances,
        "doses": [],
        "notes": [],
        "timelineEvents": [],
        "interactions": merged_interactions,
        "customUnits": [],
        "useShulginRating": False,
    }

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(snapshot, f, indent=2, ensure_ascii=False)

    if args.verbose:
        size = len(json.dumps(snapshot, indent=2, ensure_ascii=False))
        print(f"[+] Wrote {args.output} ({size / 1024:.1f} KB)", file=sys.stderr)


if __name__ == "__main__":
    main()
